apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-30T15:07:40Z"
  labels:
    app: es-manual
  name: es-manual
  namespace: elastic-dev
  resourceVersion: "33839"
  uid: db407ba6-6206-4f45-ba01-95c930fa2e09
spec:
  clusterIP: 10.97.93.30
  clusterIPs:
  - 10.97.93.30
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32040
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-manual
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}