apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elastic-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - cicd-tools-gateway
  http:
  - match:
    - uri:
        prefix: "/elastic/"
    rewrite:
      uri: /
    route:
    - destination:
        host: es-manual.elastic-dev.svc.cluster.local
        port:
          number: 9200
---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: elastic
#   namespace: istio-system
# spec:
#   host: es-manual.elastic-dev.svc.cluster.local
#   trafficPolicy:
#     tls:
#       mode: DISABLE
# ---