apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-28T19:31:52Z"
  generation: 1
  labels:
    app: kib-manual
  name: kib-manual
  namespace: elastic-dev
  resourceVersion: "142114"
  uid: 3457b5d1-98ab-4123-bb23-40b5f0281281
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kib-manual
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kib-manual
    spec:
      containers:
      - image: kibana:7.8.0
        imagePullPolicy: IfNotPresent
        name: kibana
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # Variable para Elastisearch
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://es-manual:9200/
          - name: SERVER_BASEPATH
            value: /kibana
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-09-28T19:31:52Z"
    lastUpdateTime: "2021-09-28T19:31:52Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-09-28T19:31:52Z"
    lastUpdateTime: "2021-09-28T19:31:53Z"
    message: ReplicaSet "kib-manual-65bb8cc486" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
