apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elastic-dev
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # Configuration File
    input {
      beats {
        port => "5044"
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://es-manual:9200/"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }